# Role.dcm.yml
Foundry\System\Entities\Role:
  type: entity
  repositoryClass: Foundry\System\Repositories\RoleRepository
  table: roles
  indexes:
    roles_name_index:
      columns: [ name ]
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
      length: 100
      unique: true
    created_at:
      type: datetime
    updated_at:
      type: datetime
      nullable: true