# User.dcm.yml
Foundry\System\Entities\User:
  type: entity
  repositoryClass: Foundry\System\Repositories\UserRepository
  table: users
  indexes:
    users_username_index:
      columns: [ username ]
    users_display_name_index:
      columns: [ display_name ]
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    uuid:
      type: string
      length: 36
    username:
      type: string
      length: 50
      unique: true
    email:
      type: string
      length: 255
      unique: true
    password:
      type: string
      length: 255
    display_name:
      type: string
      length: 100
    active:
      type: boolean
      options:
        default: false
    super_admin:
      type: boolean
      options:
        default: false
    timezone:
      type: string
      length: 255
      nullable: true
    last_login_at:
      type: datetime
      nullable: true
    logged_in:
      type: boolean
      options:
        default: false
    api_token:
      type: string
      length: 80
      nullable: true
      unique: true
    api_token_expires_at:
      type: datetime
      nullable: true
    created_at:
      type: datetime
      gedmo:
        timestampable:
          on: create
    updated_at:
      type: datetime
      nullable: true
      gedmo:
        timestampable:
          on: update
    deleted_at:
      type: datetime
      nullable: true
    job_title:
      type: string
      length: 50
      nullable: true
    job_department:
      type: string
      length: 50
      nullable: true
  manyToOne:
    supervisor:
      targetEntity: Foundry\System\Entities\User
      fetch: LAZY
      nullable: true
      cascade: [ persist ]
